version: "3"
services:
  jdk8-mvn-build:
    image: maven:3.8.4-openjdk-8
    container_name: jdk8-mvn-build
    privileged: true
    user: root
    #entrypoint: [ "/bin/sh","-c","wget https://dev-1306623386.cos.ap-shanghai.myqcloud.com/shell/mvn-entrypoint.sh -o /usr/local/bin/mvn-entrypoint.sh && chmod +x /usr/local/bin/mvn-entrypoint.sh && /usr/local/bin/mvn-entrypoint.sh" ]
    entrypoint: [ "/bin/sh","-c","chmod +x /usr/local/bin/mvn-entrypoint.sh && /usr/local/bin/mvn-entrypoint.sh" ]
    environment:
      - GIT_URL=https://gitee.vip/gpg-dev/my-server.git
      - GIT_USERNAME=18439406854
      - GIT_PASSWORD=1999y4m30d
    volumes:
      - /root/.m2/repository:/root/.m2/repository
      - /home:/home
      - ./mvn-entrypoint.sh:/usr/local/bin/mvn-entrypoint.sh
