apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-cli-pv
  labels:
    pv: docker-cli-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/bin/docker"
    type: File
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{.Release.Namespace}}
    name: docker-cli-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-cli-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: docker-cli-pv