apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-server
  labels:
    app.kubernetes.io/name: cloud-server
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:            # Service选择器
      app: cloud-server
  namespaceSelector:        # Namespace选择器
    matchNames:
      - {{.Release.Namespace}}
  endpoints:
    - port: metrics           # 采集节点端口（svc定义）
      interval: 10s           # 采集频率根据实际需求配置，prometheus默认15s
      path: /actuator/prometheus          # 默认地址/metrics
