apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-pv
  labels:
    pv: docker-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/var/run/docker.sock"
    type: Socket
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{.Release.Namespace}}
    name: docker-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: docker-pv