apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-pv
  labels:
    pv: git-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/.git-credentials"
    type: FileOrCreate
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{.Release.Namespace}}
    name: git-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: git-pv
