apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-pv
  labels:
    pv: docker-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/docker.sock"
    type: Socket

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pvc
  labels:
    pvc: docker-pvc
spec:
  selector:
    matchLabels:
        pv: docker-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
