apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-server-deploy
  namespace: cloud-server
  labels:
    app: cloud-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-server
  template:
    metadata:
      name: cloud-server
      labels:
        app: cloud-server
    spec:
      containers:
        - name: cloud-server
          image: registry.cn-hangzhou.aliyuncs.com/gpg_dev/cloud-server:2025-06-19-00-34-32
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_SUFFIX
              value: prod
          ports:
            - containerPort: 9099
              protocol: TCP
          resources:
            requests:
              cpu: 400m
              memory: 1024Mi
            limits:
              cpu: 800m
              memory: 2048Mi
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
            - mountPath: /home/prometheus
              name: prometheus
      restartPolicy: Always
      volumes:
        - name: docker-sock
          persistentVolumeClaim:
            claimName: docker-pv
        - name: prometheus
          persistentVolumeClaim:
            claimName: prometheus-pv