apiVersion: v1
kind: Service
metadata:
  name: cloud-web-service
spec:
  selector:
    app: cloud-web
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 3001
  type: NodePort
  